### PR TITLE
Add complex parametrized type handling

### PR DESCRIPTION
**Pull request by sschuberth**

### CODE REVIEW

**Comment by JakeWharton** [comment]
This doesn't support types with multiple generics like `Map`.

**Comment by sschuberth** [comment]
@mmarcon Could you maybe comment on this?

**Comment by spaltis** [comment]
@JakeWharton can you please provide an example JSON for which deserialization would not work?

**Comment by spaltis** [comment]
What will it take for this to be merged?

**Comment by swankjesse** [comment]
This exists; it’s called getParameterized().

**Comment by sschuberth** [comment]
Apparently getParameterized() was [added in version 2.8](https://github.com/google/gson/blob/41e48f7aa3a686778e95328693b830856538e9e3/CHANGELOG.md#L10) after this PR was created.

@spaltis Would the existing getParameterized() feature work for you?

**Comment by spaltis** [comment]
@swankjesse Is there example of handling complex parameterized type using getParameterized()?

**Comment by sschuberth** [comment]
Closing this unmerged due to a lack of interest from the project maintainers.

**Pull request closed without merging**
