### PR TITLE
Updated readme with dynamic versioning

### PR DESCRIPTION
**Pull request by talhahasanzia**
Hi,

As many libraries do this, I updated readme with dynamic versioning, with links to release versions, this make sure users check latest release version when using gson in their project.

Previously:

```gradle
dependencies {
  implementation 'com.google.code.gson:gson:2.8.5'	 
}
```

Now,

See [releases](https://github.com/google/gson/releases) for latest version.

```gradle
dependencies {
  implementation 'com.google.code.gson:gson:2.x.x'	 
}
```

Similarly Maven dependency,

Previously,

```
<dependency>
  <groupId>com.google.code.gson</groupId>
  <artifactId>gson</artifactId>
  <version>2.8.5</version>
</dependency>
```

Now,
```
<dependency>
  <groupId>com.google.code.gson</groupId>
  <artifactId>gson</artifactId>
  <version>2.x.x</version>
</dependency>
```

### CODE REVIEW

**Comment by talhahasanzia** [comment]
I signed it!

**Comment by lyubomyr-shaydariv** [comment]
I find the previous version,

```xml
<dependency>
  <groupId>com.google.code.gson</groupId>
  <artifactId>gson</artifactId>
  <version>2.8.5</version>
</dependency>
```

much easier to copy/paste. :smiley:

**Comment by talhahasanzia** [comment]
> I find the previous version,
> 
> ```
> <dependency>
>   <groupId>com.google.code.gson</groupId>
>   <artifactId>gson</artifactId>
>   <version>2.8.5</version>
> </dependency>
> ```
> 
> much easier to copy/paste. 😃

It is just a matter of opinion, lets see what general public has to say, it is easier yes, what if in some cases update is always good? like a critical bug fix, so this approach will allow user to always check for the latest version :-)

**Comment by JakeWharton** [comment]
Part of the release process is to update this so it doesn't get out of date. We too prefer the ability to directly copy/paste.

**Pull request closed without merging**
