### PR TITLE
fixed the error of printing new line for system that dont use '\n'

### PR DESCRIPTION
**Pull request by gazzdingo**
I have changed it so that it will work on more OS when you are wanting to print a new line

### CODE REVIEW

**Comment by swankjesse** [comment]
I don't think this makes sense. JSON doesn't care what OS it's being generated on.

**Comment by gazzdingo** [comment]
But on windows the pretty mode does not do pretty mode

**Comment by gazzdingo** [comment]
Because it will not do a new line

**Comment by swankjesse** [comment]
I think this is a bug in Windows. Please consider sending them a Pull Request!

**Pull request closed without merging**
