### PR TITLE
Add JsonElement.getAsDate

### PR DESCRIPTION
**Pull request by izzabudaka**
See #714

Added convenience method `public Date getAsDate(String pattern)` to get JsonPrimitive Date Strings as java.util.Date and corresponding JsonArray implementation.

### CODE REVIEW

**Comment by izzabudaka** [comment]
I signed it!

**Comment by JakeWharton** [comment]
This is a strange thing to specialize, and the asymmetry of the
implementation makes me even less excited about the prospect of its
addition.

**Comment by inder123** [comment]
Please indicate why this must be done inside Gson.

**Comment by izzabudaka** [comment]
Using Gson in multiple projects, I have found myself implementing similar Date parsing/validation functionality. I believe this change would offer greater convenience to the users. Any comments on how to make it more symmetric are welcomed :)

**Pull request closed without merging**
