### PR TITLE
Add clear method to JsonArray

### PR DESCRIPTION
**Pull request by LorenzNickel**
The method will clear the contents of a JsonArray

### CODE REVIEW

**Comment by Marcono1234** [comment]
@eamonnmcmanus could you please have a look?

For consistency a `JsonObject.clear()` method might be useful as well, but that can be done in a separate pull request, if desired.

**Comment by eamonnmcmanus** [comment]
I think if we're able to add an `asList()` method to `JsonArray`, we shouldn't need other new methods like this?

**Comment by Marcono1234** [comment]
Right, though the open question with `asList()` is still `null` handling I think.

Maybe `clear()` is needed often enough to justify having it directly on `JsonArray` either way? But I am not too sure.

**Comment by eamonnmcmanus** [comment]
I think object reuse is poor practice so I don't find that a convincing argument. If people really want to reuse `JsonArray` instances they can do `array.asList().clear()`. But making a new `JsonArray` is generally better. So I'm still unconvinced by `JsonArray.clear()`, and even more so by `JsonObject.clear()`.

**Comment by dhoard** [comment]
> I think object reuse is poor practice so I don't find that a convincing argument. If people really want to reuse `JsonArray` instances they can do `array.asList().clear()`. But making a new `JsonArray` is generally better. So I'm still unconvinced by `JsonArray.clear()`, and even more so by `JsonObject.clear()`.

Fair enough.

**Pull request closed without merging**
