### PR TITLE
added method to fetch next string into OutputStream

### PR DESCRIPTION
**Pull request by rodnaph**
Related open issue: https://github.com/google/gson/issues/415

This PR is without much thought or tests yet, but I'm opening it to get some feedback on if this would be a potential addition, and how i'd go about doing that.

The use-case this patch solves (as described in the other ticket) is that sometimes JSON documents can contain very large values (base64 encoded file content in my case) which you don't want to have to realise in memory at once.  This allows reading these sections into an OutputStream which can write it to a file for example.

### CODE REVIEW

**Comment by rodnaph** [comment]
I signed it!

**Comment by swankjesse** [comment]
I like the idea, but as-is I want two changes:

1. Strings should be a character stream, not as a byte stream.
2. The stream should be something you pull from, not something you push into.

So the API probably wants to be this:

```
public Reader nextStringReader();
```

That reader returns the characters of the JSON string, unescaping them as necessary. We’ll also need tests, particularly tests that check things like `\t` and `\u0020` are properly unescaped.

**Comment by rodnaph** [comment]
1. Sure
2. With `nextStringReader`, I assume it would then be the responsibility of the caller to ensure they've consumed the entire stream before fetching the next token? For example...

```
Reader r = reader.nextStringReader();
int i = reader.nextInt();
```

When calling `nextInt` the Reader needs to be been drained or skipped to avoid buffering it in memory.  I guess buffering it in memory could be the default behaviour if you have not consumed it already yourself?

**Comment by swankjesse** [comment]
I think we should throw an IllegalStateException if you attempt to access the stream after the underlying JsonReader has advanced.

**Pull request closed without merging**
