### PR TITLE
Added support to serialize/deserialize ConcurrentMap and ConcurrentNa…

### PR DESCRIPTION
**Pull request by inder123**
…vigableMap. This fixes https://github.com/google/gson/issues/624

### CODE REVIEW

**Comment by swankjesse** [comment]
Isn't this like, particularly sketchy? Because it might be changing as we encode?

**Comment by inder123** [comment]
@swankjesse Please explain what you mean by "encode". 
We already do something similar for Maps (use LinkedHashMap), and List. This is just an extension to support additional java.util.concurrent classes.

**Comment by swankjesse** [comment]
It's very weird to serialize a value that's under active modification. When would you do this?

**Comment by inder123** [comment]
Where is it under active modification? Are you saying it because it is a concurrent map?

**Comment by inder123** [comment]
For that matter, ANY java object can be under active modification while Gson is serializing it.

**Comment by swankjesse** [comment]
Works for me. I still think code that does this is weird, but I can imagine non-weird use cases.

**Pull request merged**
