### PR TITLE
Update EnumMap serialization logic to handle SerializedName annotatio…

### LINKED ISSUE #473: SerializedName does not work with enum types in EnumMap
```
What steps will reproduce the problem?
1. Defining an enum type such as:
public enum Test {
    @SerializedName("aaa")
    A,
    @SerializedName("bbb")
    B,
    @SerializedName("ccc")
    C
}

2. Testing the enum type with a EnumMap class, such as:

Gson gson = new Gson();
System.out.println(gson.toJson(Test.A));
System.out.println(gson.toJson(Test.B));
System.out.println(gson.toJson(Test.C));

Map<Test, Integer> testMap = new EnumMap<Test, Integer>(Test.class);
testMap.put(Test.A, 3);
testMap.put(Test.B, 2);
testMap.put(Test.C, 1);
System.out.println(gson.toJson(testMap));

What is the expected output? What do you see instead?
I would expect to have an output like this:
"aaa"
"bbb"
"ccc"
{"aaa":3,"bbb":2,"ccc":1}

However, the EnumMap class does not seem to take into account the 
@SerializedName annotation, and I obtain this instead:
"aaa"
"bbb"
"ccc"
{"A":3,"B":2,"C":1}

What version of the product are you using? On what operating system?
I'm using Gson 2.2.2 in Windows 7

Please provide any additional information below.
This problem is present in both serialization and deserialization. I have a 
Json file that I cannot modify, with map fields such as "Item_Value#Parameter". 
I would like to deserialize it avoiding the use of a Map<String, Integer> class 
if possible.
```

Original issue reported on code.google.com by `FernA...@gmail.com` on 22 Sep 2012 at 2:11

### LINKED ISSUE #562: Serialization: Map<CustomEnum,XXX> -> @SerializedEnum is ignorred in enum's values
```
What steps will reproduce the problem?
class Test{
   Map<OS,String> natives = new HashMap<OS,String>();
public Test(){
natives.put(OS.Windows,"1");
natives.put(OS.MacOSX,"1");
}
}

enum OS{
@SerializedName("windows")
Windows,
@SerializedName("unix")
Linux,
@SerializedName("osx")
MacOSX
}

Gson gson = new Gson();
gson.toJson(new Test());

What is the expected output? What do you see instead?
Expected:
{
natives{
"windows":"1",
"osx":"2"
}
}

Current:
{
natives{
"Windows":"1",
"MacOSX":"2"
}
}

What version of the product are you using? On what operating system?
Mac OS X 10.9
google-gson-2.2
java 1.6

Please provide any additional information below.

```

Original issue reported on code.google.com by `yan.zait...@gmail.com` on 24 Feb 2014 at 9:32

### PR DESCRIPTION
**Pull request by sweatybridge**
…ns on enums - fix #473 and fix #562

### CODE REVIEW

**Comment by sweatybridge** [comment]
I signed it!

**Comment by swankjesse** [comment]
This is not the right fix for the problem. The right solution is to use `enableComplexMapKeySerialization()` on your GsonBuilder.

```
  enum Bool {
    @SerializedName("yes") TRUE,
    @SerializedName("no") FALSE
  }

  public void testEnumSerializedName() {
    Map<Bool, Integer> map = new LinkedHashMap<Bool, Integer>();
    map.put(Bool.TRUE, 1);
    map.put(Bool.FALSE, 2);

    Gson gson = new GsonBuilder()
        .enableComplexMapKeySerialization()
        .create();

    Type type = new TypeToken<Map<Bool, Integer>>() {}.getType();
    String json = gson.toJson(map, type);
    assertEquals("{\"yes\":1,\"no\":2}", json);
    assertEquals(map, gson.fromJson(json, type));
  }
```

**Comment by duongnt1991** [comment]
I signed it!

**Comment by duongnt1991** [comment]
Hi swankjesse, please build your library.
I cant re-build it to jar :(

**Comment by renjithy85** [comment]
> This is not the right fix for the problem. The right solution is to use `enableComplexMapKeySerialization()` on your GsonBuilder.
> 
> ```
>   enum Bool {
>     @SerializedName("yes") TRUE,
>     @SerializedName("no") FALSE
>   }
> 
>   public void testEnumSerializedName() {
>     Map<Bool, Integer> map = new LinkedHashMap<Bool, Integer>();
>     map.put(Bool.TRUE, 1);
>     map.put(Bool.FALSE, 2);
> 
>     Gson gson = new GsonBuilder()
>         .enableComplexMapKeySerialization()
>         .create();
> 
>     Type type = new TypeToken<Map<Bool, Integer>>() {}.getType();
>     String json = gson.toJson(map, type);
>     assertEquals("{\"yes\":1,\"no\":2}", json);
>     assertEquals(map, gson.fromJson(json, type));
>   }
> ```

This is not solving my problem with EnumMap. I am still facing com.google.gson.JsonSyntaxException: duplicate key: null.

json "orderDimension": {
          "0": 5,
          "1": 10
        }
Here is orderDimension

public class Dimension {
    private EnumMap<DimensionEnum,Integer> orderDimension;
}

public enum DimensionEnum {
    ORDER_CAPACITY,
    CRATE_CAPACITY,
    KG_CAPACITY
}

**Pull request closed without merging**
