### PR TITLE
Port tests from JUnit 3 to JUnit 4

### PR DESCRIPTION
**Pull request by MaicolAntali**
I haveI have port test from Junit 3 to Junit 4. 

⚠️ **I still working on it so consider this PR as a draft**

### CODE REVIEW

**Comment by MaicolAntali** [comment]
All test runs except one: EnumWithObfuscatedTest.testEnumClassWithObfuscated()

The stacktrace of the error is:

```
-------------------------------------------------------------------------------
Test set: com.google.gson.functional.EnumWithObfuscatedTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.002 s <<< FAILURE! - in com.google.gson.functional.EnumWithObfuscatedTest
com.google.gson.functional.EnumWithObfuscatedTest.testEnumClassWithObfuscated  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "com.google.gson.Gson.fromJson(String, java.lang.Class)" because "this.a" is null
	at com.google.gson.functional.EnumWithObfuscatedTest.testEnumClassWithObfuscated(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:377)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:284)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:248)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:167)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

```

I try to debug it, but any idea/hint is appreciated

**Comment by MaicolAntali** [comment]
> 1\. Can you avoid moving methods around? It makes reviewing harder.
> 2\. Some of the formatting changes are a bit distracting. Fixing indentation to be consistent with Google style (+4 continuation lines) is good, but for example there's no need to split `new TypeToken<Foo>() {}.getType()` between the braces.

For the code formatting I have used the [IntelliJ Java Google Style file](https://raw.githubusercontent.com/google/styleguide/gh-pages/intellij-java-google-style.xml). Is it not a good choice?


> 3\. Your test failure is due to a subtle problem with ProGuard. `EnumWithObfuscatedTest` verifies that enum serialization works even when the code is processed by ProGuard. The ProGuard configuration [here](https://github.com/google/gson/blob/4aaf1385db5ffbc99de7411e5e80201fd8da7f3c/gson/src/test/resources/testcases-proguard.conf#L17) needs to be adjusted to reflect the change of `setUp` from `protected` to `public`. (That ProGuard just silently ignores `setUp` because it's specified with the wrong modifier seems pretty hostile to me, but there it is.)

 I'll look into it, thanks!

**Comment by eamonnmcmanus** [comment]
I would recommend the [google-java-format IntelliJ plugin](https://plugins.jetbrains.com/plugin/8527-google-java-format) and only formatting changed lines. To be honest I don't really know the status of that style file.

**Comment by MaicolAntali** [comment]
Ohhh ok, thank you 😃

**Review by eamonnmcmanus — CHANGES_REQUESTED** [review]
I'm really feeling that this change is much more extensive than I would have expected, or indeed wanted. Would you mind starting over, and this time _only_ doing what the PR description says, porting from JUnit 3 to JUnit 4? So no moving things around and no formatting changes. Changing the assertions is still OK if you want, for example `assertEquals(true, x)` to `assertTrue(x)`, but I think even those will follow automatically when we port the assertions to Truth. I'd be happiest if the only diffs I saw were the removal of `TestCase`, the addition of `@Test`, the adjustment of `setUp()` and `tearDown()` methods, and necessary changes to imports. Reorganizing the imports to follow Google style is OK if you are changing them anyway.

The formatting changes should happen later, in one go, when we reformat all the source code with google-java-format.

My point here is that it should be easy to review these changes, and it should be easy when looking at the history of these files to understand exactly what this PR was about.

**Comment by MaicolAntali** [comment]
Yes, I can do it.

I close this PR.

**Pull request closed without merging**
