### PR TITLE
Strictness follow-up

### PR DESCRIPTION
**Pull request by Marcono1234**
### Purpose
Follow-up for #2323

### Description
- Remove mentions of `null` Gson strictness; this is an implementation detail
- Fix incorrect / outdated documentation
- Reduce links to RFC; if there is already a link to it in a previous sentence don't link to it again
- Extend and update tests
- Minor punctuation changes in documentation for consistency
- Deprecate `setLenient` methods

Feedback is appreciated, especially regarding the documentation changes. Some changes might be a bit opinionated, so no problem if you disagree and want me to change anything.
@marten-voorberg, are these changes ok for you and still in the spirit of what you originally had in mind? Of course if you want to change anything else, feel free to either suggest it here or create an additional pull request as well.

### Checklist

- [x] New code follows the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html)
- [x] If necessary, new public API validates arguments, for example rejects `null`
- [x] New public API has Javadoc
    - [x] Javadoc uses `@since $next-version$`  
      (`$next-version$` is a special placeholder which is automatically replaced during release)
- [x] If necessary, new unit tests have been added  
  - [x] Assertions in unit tests use [Truth](https://truth.dev/), see existing tests
  - [x] No JUnit 3 features are used (such as extending class `TestCase`)
  - [x] If this pull request fixes a bug, a new test was added for a situation which failed previously and is now fixed
- [x] `mvn clean verify javadoc:jar` passes without errors

### CODE REVIEW

**Comment by marten-voorberg** [comment]
Thanks for taking care of these points. How are we doing here @Marcono1234 @eamonnmcmanus now? It seems to me like we are done and we can merge strictness into main soon

**Comment by Marcono1234** [comment]
From my side the main open question was whether you @marten-voorberg are fine with the changes in this pull request, since you were the one who had the idea about this strict mode and performed the actual implementation.

Could be the case though that Éamonn has some additional suggestions for this pull request.

**Review by marten-voorberg — APPROVED** [review]
LGTM

**Comment by marten-voorberg** [comment]
Everything looks fine to me :+1:

**Comment by eamonnmcmanus** [comment]
This all looks good. Thanks! I'm going to run it against all of Google's internal tests and if that doesn't reveal any problems I think we can go ahead and merge this into `main`.

**Comment by Marcono1234** [comment]
@eamonnmcmanus were the tests successful, or didn't you get to run the tests yet?

**Comment by eamonnmcmanus** [comment]
Sent #2437 for review.

**Pull request merged**
