### PR TITLE
Add static method alternatives to JsonParser

### PR DESCRIPTION
**Pull request by Degubi**
Alternative request to add static methods to JsonParser. This way no bytecode changes. I didn't mark the constructor as deprecated this time to avoid warnings.  The PR adds 3 new static methods to JsonParser and refactors the existing 3 instance methods to use the static ones.

### CODE REVIEW

**Comment by asus246** [comment]
ok

**Comment by inder123** [comment]
What is the key issue you are trying to solve? 
Is it the creation of the JsonParser object that is bothering you? Or is it a deeper philosophical issue.

**Comment by Degubi** [comment]
I just don't like the look of it. And the need to create a new parser object every time. Also, the method names "parse" vs "parseString" I can see that I'm parsing the Json from a string, not from a Reader.

**Comment by Marcono1234** [comment]
@Degubi why did you close this pull request?

You were definitely not the only one with this opinion, see [this StackOverflow comment](https://stackoverflow.com/questions/4110664/gson-directly-convert-string-to-jsonobject-no-pojo#comment30505372_4527044)

**Comment by Degubi** [comment]
@Marcono1234 I reopened it with better deprecations, see #1513 . I really think it they should be statics, but I'm not sure about others thinking the same... (See the discussion in #1513)

**Pull request closed without merging**
