### PR TITLE
Perf: Moving string length calculation to local variable.

### PR DESCRIPTION
**Pull request by arriolac**
Performance improvement by moving string length calculation to local variable. Previous implementation calculated the string's length for each each loop iteration.

### CODE REVIEW

**Comment by arriolac** [comment]
I signed it!

**Comment by swankjesse** [comment]
This method is intrinsic.

**Comment by arriolac** [comment]
Yikes. I thought `length()` was O(n). However, this is still a very minor pref improvement because of the cost of making a method call.

**Comment by swankjesse** [comment]
The cost of the method call is like, actually zero. You should send us performance improvements, but they should be based on performance problems, not speculation.

**Comment by swankjesse** [comment]
Thanks for the PR though. I want you to send me something that makes a measured improvement, with before/after benchmarks!

**Pull request closed without merging**
