### PR TITLE
Build for Java 8 rather than Java 7.

### LINKED ISSUE #2743: Make Java 8 the minimum supported version
Java 8 has been around for 10 years now and I think it is reasonable to drop support for earlier versions. With Java 8, we can simplify some code by using lambdas and method references. We can also support serializing and deserializing types like `Optional` and `Instant`. And we can add `default` and `static` methods to interfaces in the API.

We already have the [java8](https://github.com/google/gson/labels/java8) label for issues that can be solved once Java 8 is required. This issue just tracks making that happen.

### PR DESCRIPTION
**Pull request by eamonnmcmanus**
Closes #2743.

### CODE REVIEW

**Review by cpovirk — APPROVED** [review]
A few notes, mostly on the Android front:

- I see that you already have [an Animal Sniffer check for Android compatibility](https://github.com/google/gson/blob/3ce6eb87983dd71bf6b47ff64645398e9caf8d14/pom.xml#L504). We seem to be getting good results [in Guava](https://github.com/google/guava/blob/e5b58e2fc8561192338dfe0c68c0bce27066a6aa/android/pom.xml#L287) from the https://github.com/open-toast/gummy-bears signatures that you mention, the ones that assume only [the always-on desugaring of a smallish set of methods](https://github.com/open-toast/gummy-bears?tab=readme-ov-file#android). Those are safe to use even if your users don't opt in to the more extensive feature that we normally refer to as "library desugaring," so you might have a look if javac starts generating usages of those methods automatically(?) or if you just want a smattering of Java 8 goodies.
- I don't see any issues with conditional support for `Optional` and `Instant` and friends. Once you've checked that the classes exist (see sub-bullet), you'll now be able to write normal Java code to operate on those classes. Android doesn't even mind if you have random methods in a class with `Optional` and `Instant` in the signature (in contrast to Java, which would, IIUC) as long as you don't call them.
   - I imagine the best way to guard that support will be with Java reflection that looks up those classes. I would _hope_ that that would support both the case of Android versions new enough to support the classes directly and the case of desugaring (which I _hope_ is smart enough to rewrite strings used in reflection). I have made the mistake before of just trying to use the classes and then catching the resulting error, but I have learned [one](https://github.com/google/truth/issues/333#issuecomment-765616282) or [two](https://github.com/google/guava/commit/fb109b051c9ec48d5e77bf73b33a228ab5d57462) (see also internal thread "Android and java7 Futures.getChecked()" about log spam) lessons about that, at least one of which is unlikely to be news to you :)).
- I have seen a handful of problems when experimenting with adding `default` methods in Guava inside Google. (See bug 229266760.) One of them is a result of a system that ill-advisedly tries to use a mix of the internal Guava and the external Guava (with the external Guava still lacking the `default` method), but I'm not sure I ever had a theory for the other. Anyway, adding the `default` methods would _probably_ work fine, but I'd advise factoring in at least a little possibility that it turns out not to.
- Lambda and method references should be entirely fine :) Maybe also remove some unnecessary `final` keywords from effectively final variables if you have any of those hanging around.
- Kudos on actually using `--release` to avoid [`ByteBuffer` issues](https://github.com/google/guava/issues/3990) (not that GSON appears to use the class) and other horrors.

**Review by Marcono1234 — APPROVED** [review]
If you want you can also adjust the build setup to properly support JDK 21, since the only blocking thing was using Java 7 as target. So basically your changes from #2690, except:
- Omit the `JAPICMP-OLD` changes (that has already been solved)
- In the README, adjust
  > JDK 17 is recommended. Newer JDKs are currently not supported for building

This would then close #2501

Or alternatively I can also do that in a separate PR if you prefer.

----

It seems there are also a few comments in the code suggesting refactoring for Java 8:
- These Error Prone patterns can probably be enabled now, but might introduce a lot of new warnings; so maybe worth doing in a separate PR?
https://github.com/google/gson/blob/3ce6eb87983dd71bf6b47ff64645398e9caf8d14/pom.xml#L283-L286
- Using `Executable` might simplify the code, but it seems Android only has it [since API level 26](https://developer.android.com/reference/kotlin/java/lang/reflect/Executable) so we cannot use it yet.
https://github.com/google/gson/blob/3ce6eb87983dd71bf6b47ff64645398e9caf8d14/gson/src/main/java/com/google/gson/internal/reflect/ReflectionHelper.java#L131-L132
- https://github.com/google/gson/blob/3ce6eb87983dd71bf6b47ff64645398e9caf8d14/gson/src/main/java/com/google/gson/internal/NonNullElementWrapperList.java#L130

**Comment by eamonnmcmanus** [comment]
OK, I'm proposing to merge this change as is and address any comments in followups. @Marcono1234 if you want to send PRs for the items you mention, I would certainly appreciate that.

**Comment by cpovirk** [comment]
(I forgot to mention that Animal Sniffer will be upset about any appearance of `Optional` or `Instant` in a signature or method body. We suppress similar problems in Guava. Another alternative would be to investigate using multi-release jars, except for the part that that wouldn't actually help on Android.)

**Pull request merged**
