### PR TITLE
Support omitting default values

### LINKED ISSUE #459: Allow ExclusionStrategy by field value.
```
When implementing the ExclusionStrategy, in shouldSkip* methods we have access 
to the fields attributes but not the fields values.

Might be usefull to be able to filter based on some specific values. So the 
idea here is to enhance the ExclusionStrategy to pass not just FieldAttributes 
but also the source object itself.
```

Original issue reported on code.google.com by `jean-m...@spaggiari.org` on 3 Jul 2012 at 6:30

### PR DESCRIPTION
**Pull request by sschuberth**
Functionality is based on

https://groups.google.com/forum/#!msg/google-gson/pk2vAcUk5rQ/SUCK2C4DY10J
https://groups.google.com/forum/#!msg/google-gson/pk2vAcUk5rQ/q6Pet53qgjIJ

Fixes #459.

### CODE REVIEW

**Comment by spaltis** [comment]
Can this be merged?

**Comment by sschuberth** [comment]
@JakeWharton @swankjesse @inder123 Could we please get *any* feedback on whether this has a chance to get merged any time soon, or whether it makes sense to close it unmerged?

**Comment by swankjesse** [comment]
I’m not in favor of adding this feature at this time.

**Comment by spaltis** [comment]
why not?

**Comment by sschuberth** [comment]
And why not "at this time"? I.e., what could make you chance your opinion over time?

**Comment by sschuberth** [comment]
Closing this unmerged due to a lack of interest from the project maintainers.

**Pull request closed without merging**
