### PR TITLE
Avoid returning incomplete TypeAdapters in concurrent calls

### PR DESCRIPTION
**Pull request by mwalkerr**
Resolves google/gson#1829
Resolves google/gson#625 partially

In the current implementation, a `TypeAdapter` may be added to the `typeTokenCache` despite having a `FutureTypeAdapter` with a null delegate as part of its definition. This would occasionally cause us to see an `IllegalStateException` from GSON. This would happen when bringing up an application in a docker container and then running parallelized API tests against it. Some of the objects the application deserializes are recursively defined such as `A` -> `B` -> `A`. I believe what was happening was that one thread would start to deserialize `A` and call to `getAdapter(A)` which would call to `getAdapter(B)` which would call `getAdapter(A)`, which would return the `FutureTypeAdapter` for `A`. Before the first thread is able to update the delegate for the `FutureTypeAdapter` for `A`, another thread tries to deserialize `B`, calls `getAdapter(B)`, and retrieves the entry added by the first thread which contains a `TypeAdapter` for `A` which is a `FutureTypeAdapter` with a null delegate

### CODE REVIEW

**Comment by mwalkerr** [comment]
@googlebot

**Comment by mwalkerr** [comment]
@googlebot I signed it!

**Comment by mwalkerr** [comment]
I used the following test to verify the issue and the solution:

```
package com.google.gson.regression;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import junit.framework.TestCase;

import java.lang.reflect.Field;
import java.util.Map;
import java.util.concurrent.CyclicBarrier;

public class RecursiveTypeRaceConditionTest extends TestCase {
  private final Gson gson = new Gson();

  public void testNullSafeBugSerialize() throws Exception {
    for (int i=0;i<100000;i++){
      Field f = gson.getClass().getDeclaredField("typeTokenCache");
      f.setAccessible(true);
      ((Map) f.get(gson)).clear();
      final CyclicBarrier gate = new CyclicBarrier(3);
      final boolean[] exception = {false};
      Thread t1 = new Thread(new Runnable() {
        @Override
        public void run() {
          try {
            gate.await();
            gson.getAdapter(TypeToken.get(A.class)).fromJson("{\"b\": {\"a\":{}}}");
          } catch (Exception e) {
            exception[0] = true;
            e.printStackTrace();
          }
        }
      });
      Thread t2 = new Thread(new Runnable() {
        @Override
        public void run() {
          try {
            gate.await();
            gson.getAdapter(TypeToken.get(B.class)).fromJson("{\"a\": {\"b\":{}}}");
          } catch (Exception e) {
            exception[0] = true;
            e.printStackTrace();
          }
        }
      });
      t1.start();
      t2.start();
      gate.await();
      t1.join();
      t2.join();
      assertFalse(exception[0]);
    }
  }

  private static final class A {
    B b;
  }
  private static final class B {
    A a;
  }
}
```

**Comment by Marcono1234** [comment]
Thanks a lot for you work on this! This has now be fixed by #1832, but thank you nonetheless!

**Pull request closed without merging**
